name: Windows Compile with SQLite

on:
  workflow_dispatch: # Abilita l'avvio manuale e la scelta del commit/branch

jobs:
  build:
    # non uso windows-latest solo per usare vs2022
    runs-on: windows-2022

    steps:
    # 1. Scarica il codice del repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Installa SQLite3 tramite vcpkg
    - name: Install SQLite3 via vcpkg
      run: vcpkg install sqlite3:x64-windows

    # 3. Configura CMake integrando vcpkg per trovare SQLite3
    - name: Configure CMake
      run: cmake --preset msbuild-msvc

    # 4. Compila l'applicazione in modalità Release
    - name: Build Application
      run: cmake --build --preset msbuild-msvc-release

    # 5. Copia la DLL di SQLite nella cartella di build di Release
    - name: Copy SQLite DLL to build folder
      run: xcopy "C:\vcpkg\installed\x64-windows\bin\sqlite3.dll" "build\Release\" /Y

    # 5. Salva l'eseguibile (.exe) e la DLL di SQLite come artefatti
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: applicazione-windows-x64
        path: |
          build/Release/sqlite_c_demo.exe
          build/Release/sqlite3.dll
